'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.4961
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class OMN3011

    '''<summary>
    '''hidMode コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents hidMode As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''btnNew コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnNew As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDell コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnDell As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCHG コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnCHG As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''udpSubmit コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents udpSubmit As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlKey コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents pnlKey As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''MODE コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents MODE As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''udpKEY コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents udpKEY As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnAJKEY コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnAJKEY As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbltRENNO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lbltRENNO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''udpRENNO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents udpRENNO As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnAJRENNO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnAJRENNO As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RENNO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents RENNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''JIGYOCD コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents JIGYOCD As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''SAGYOBKBN コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SAGYOBKBN As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''NONCD コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents NONCD As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''btnRENNO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnRENNO As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbltGOUKI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lbltGOUKI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''udpGOUKI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents udpGOUKI As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnAJGOUKI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnAJGOUKI As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GOUKI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents GOUKI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnGOUKI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnGOUKI As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSearch コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''udpSearch コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents udpSearch As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnAJSearch コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnAJSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlMain コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents pnlMain As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbltNONYUCD コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lbltNONYUCD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NONYUCD コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents NONYUCD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NONYUNM1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents NONYUNM1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NONYUNM2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents NONYUNM2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbltTENKENYMD コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lbltTENKENYMD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TENKENYMD コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TENKENYMD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnTENKENYMD コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnTENKENYMD As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lbltKISHUKATA コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lbltKISHUKATA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KISHUKATA コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KISHUKATA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbltSAGYOTANTCD コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lbltSAGYOTANTCD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SAGYOTANTCD コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SAGYOTANTCD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSAGYOTANTCD コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSAGYOTANTCD As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''udpSAGYOTANTNM コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents udpSAGYOTANTNM As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnAJSAGYOTANTNM コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnAJSAGYOTANTNM As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SAGYOTANTNM コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SAGYOTANTNM As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbltYOSHIDANO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lbltYOSHIDANO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''YOSHIDANO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents YOSHIDANO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbltSAGYOTANNMOTHER コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lbltSAGYOTANNMOTHER As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SAGYOTANNMOTHER コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SAGYOTANNMOTHER As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbltSHUBETSUCD コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lbltSHUBETSUCD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SHUBETSUCD コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SHUBETSUCD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SHUBETSUNM コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents SHUBETSUNM As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbltSTARTTIME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lbltSTARTTIME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''STARTTIME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents STARTTIME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbltitle1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lbltitle1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ENDTIME コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ENDTIME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UMU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UMU As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbltKYAKUTANTCD コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lbltKYAKUTANTCD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''KYAKUTANTCD コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents KYAKUTANTCD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlMei コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents pnlMei As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''udpTABU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents udpTABU As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''NowIndex コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents NowIndex As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''OldIndex コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents OldIndex As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''TABU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TABU As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''menu1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents menu1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblTTGYONO コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblTTGYONO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTTHSYOSAIMONG コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblTTHSYOSAIMONG As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTTINPUTNAIYOU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblTTINPUTNAIYOU As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTTTENKENUMU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblTTTENKENUMU As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTTCHOSEIUMU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblTTCHOSEIUMU As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTTKYUYUUMU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblTTKYUYUUMU As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTTSIMETUKEUMU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblTTSIMETUKEUMU As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTTSEISOUUMU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblTTSEISOUUMU As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTTKOUKANUMU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblTTKOUKANUMU As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTTSYURIUMU コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblTTSYURIUMU As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTTFUGUAIKBN コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lblTTFUGUAIKBN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel1 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnAJLVSearch コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnAJLVSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ScrollSet コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents ScrollSet As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''LVSearch コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents LVSearch As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''pnlMain2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents pnlMain2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbltHOZONSAKI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lbltHOZONSAKI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HOZONSAKI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents HOZONSAKI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbltTOKKI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents lbltTOKKI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TOKKI コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents TOKKI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAJModeCng コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnAJModeCng As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAJNext コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnAJNext As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAJF2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnAJF2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAJSubmit コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnAJSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAJF4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnAJF4 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAJF5 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnAJF5 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAJPre コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnAJPre As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAJF7 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnAJF7 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAJExcel コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnAJExcel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAJBefor コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnAJBefor As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAJclear コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnAJclear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnNext コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnNext As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnF2 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnF2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSubmit コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnF4 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnF4 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnF5 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnF5 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPre コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnPre As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnF7 コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnF7 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnExcel コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnExcel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBefor コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnBefor As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnclear コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナ ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents btnclear As Global.System.Web.UI.WebControls.Button

End Class
